### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by sntran** [backslash47/xmldom#1]
## Steps to reproduce

```node.js
const XMLDom = require('xmldom-ts');
```

## Expected result:

No error.

## Actual result

```node.js
ReferenceError: globalThis is not defined
```

Node version: v10.13.0

I understand that the requirement of this library is Node v12, but since I can't upgrade yet , I can't check if `globalThis` is defined there.

However, I think we can at least get around that by checking `typeof globalThis` instead:

https://github.com/backslash47/xmldom/blob/3fbfe8825dd746bef287c31a6d666630339cebba/src/index.ts#L35

**Comment by yurist38** [comment]
Hi! Just faced this issue too... :( Any updates on this, guys? Are you okay if anybody opens a PR with the fix?

[UPDATE] I've managed to handle this issue by including [this polyfill](https://www.npmjs.com/package/@ungap/global-this) to my code. It's working now but probably it could make sense to handle it on this side rather than on the package consumer's side.

**Comment by khusamov** [comment]
```
***\node_modules\xmldom-ts\src\index.ts:37
if (globalThis) {
^
ReferenceError: globalThis is not defined
    at Object.<anonymous> (D:\REPO\github\zevs-lite\node_modules\xmldom-ts\src\index.ts:37:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

```

**Comment by backslash47** [comment]
Please, create the PR. I will review it.

Important is so the module will work in browser and also in NodeJS environment.
